### ISSUE TITLE
 Scale 19x Work Party #2 Checklist

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#402]
## Description

One-day work party 

Date: November 6
Location: Pasadena Public Storage

Agenda:
  - Monitoring:
    - [ ] @sbibayoff to demo his monitoring solution
    - [ ] Game plan for automation around monitoring automation
- Switches:
  - [x] Test all switches, confirm they still boot primary partition.
  - [x] High Temps in switches indicate need for cleaning #350
  - [ ]  Evaluate labeling Renumber and relabel switches #138

Previous work pary work that was completed: 
- https://github.com/socallinuxexpo/scale-network/issues/386

## Acceptance Criteria
What is the expected outcome that resolves this issue?

**Comment by sarcasticadmin** [comment]
Closing as this work party for 19x has passed
