### ISSUE TITLE
Work Party #1 Nov. 18-19 2023 - Checklist

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#632]
## Description

```
Null Space
2522 N Ontario St, Burbank, CA 91504

Nov. 18-19, 2023 9AM-Dark Pacific Time
```

Items:
- [x] Test New Trailer for moving our gear (Good to go)
- [x] Review 21x Supply Requests: https://github.com/socallinuxexpo/scale-network/issues/602
- [x] Check the Gaffer Tape Inventory
- [x] Finalize decision around purchasing new hardware (belkin 3200) #532 
- [x] Test out switch config tooling https://github.com/socallinuxexpo/scale-network/pull/626
- [x] Re-serialize the APs https://github.com/socallinuxexpo/scale-network/issues/579
- [ ] ~Repack all cables (ideally in sets by room, but by length if necessary)~
- [x] Proper labels on boxes via labeller (completed in 2nd workparty 1/13/24-1/14/24)
- [x] Monitoring Server Configuration (post party)  https://github.com/socallinuxexpo/scale-network/pull/642
- [ ] Checklists: 
  - [ ] Workparties https://github.com/socallinuxexpo/scale-network/issues/244
  - [ ] Show https://github.com/socallinuxexpo/scale-network/issues/245
  - [ ] Teardown https://github.com/socallinuxexpo/scale-network/issues/243
  - [ ] Repo https://github.com/socallinuxexpo/scale-network/issues/434
> Feel free to update with anything Ive missed

## Acceptance Criteria
- Have a productive Work Party

**Comment by sarcasticadmin** [comment]
Gaffer tape -  2 year supply
Repack all cables (ideally in sets by room, but by length if necessary) - Already done from 21x cleanup

**Comment by sarcasticadmin** [comment]
@sbibayoff @owendelong @davidelang were did we land with the  `Proper labels on boxes via labeller`? I feel like that was pretty much wrapped but by sunday

Overall I think we had a very productive work party! Thank you to all who were able to participate!

**Comment by owendelong** [comment]
I think there is still work to do, but much progress was made.

Owen
